name: Build DexIdentity

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dex-identity:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Install DexIdentity dependencies
        run: dotnet restore "DexIdentity.csproj"

      - name: Build DexIdentity C# project
        run: dotnet build "DexIdentity.csproj" --configuration Release --no-restore

      - name: Create DexIdentity release artifacts
        run: dotnet publish "DexIdentity.csproj" --configuration Release --no-restore --no-build --output dist

      - shell: pwsh
        name: Zip DexIdentity release artifacts
        run: Compress-Archive -Path dist/* -DestinationPath dist/dexidentity.zip

      - name: Upload DexIdentity zipped artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: dexidentity.zip
          path: dist/
          if-no-files-found: error
          retention-days: 90

  deploy-dex-identity:
    runs-on: ubuntu-20.04
    needs: [build-dex-identity]

    steps:
      - name: Download DexIdentity artifacts
        uses: actions/download-artifact@v2.0.6
        with:
          name: dexidentity.zip
          path: artifacts

      - shell: bash
        name: Login to Azure
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - shell: bash
        name: Deploy DexIdentity to Azure
        run: |
          az webapp deployment source config-zip -g djr-rg-dex -n dexidentity --src artifacts/dexidentity.zip
